version: '3.8'

services:
  # Default configuration (always scans github.com, gitlab.com, bitbucket.org)
  jenkins-agent-default:
    build: .
    image: jenkins-agent-ssh:latest
    container_name: jenkins-agent-default
    environment:
      # Only always-scanned hostnames will be included
      - SSH_KEYSCAN_ENABLED=true

  # Additional hostnames using new format
  jenkins-agent-with-additional:
    build: .
    image: jenkins-agent-ssh:latest
    container_name: jenkins-agent-with-additional
    environment:
      - HOSTNAMES_TO_SCAN_1=git.company.com,svn.legacy.com
      - HOSTNAMES_TO_SCAN_DEV=dev.gitlab.com
      - SSH_KEYSCAN_ENABLED=true

  # Multiple groups of hostnames
  jenkins-agent-multi-env:
    build: .
    image: jenkins-agent-ssh:latest
    container_name: jenkins-agent-multi-env
    environment:
      - HOSTNAMES_TO_SCAN_PROD=prod.git.company.com,secure.bitbucket.com
      - HOSTNAMES_TO_SCAN_STAGING=staging.gitlab.com
      - HOSTNAMES_TO_SCAN_LEGACY=old.svn.server.com
      - SSH_KEYSCAN_ENABLED=true

  # Disabled keyscan (no hostnames will be scanned, including always-scanned)
  jenkins-agent-disabled:
    build: .
    image: jenkins-agent-ssh:latest
    container_name: jenkins-agent-disabled
    environment:
      - SSH_KEYSCAN_ENABLED=false

  # Legacy SSH_HOSTNAMES still supported (always-scanned hosts are still included)
  jenkins-agent-legacy:
    build: .
    image: jenkins-agent-ssh:latest
    container_name: jenkins-agent-legacy
    environment:
      - SSH_HOSTNAMES=git.example.com,custom.host.com
      - SSH_KEYSCAN_ENABLED=true